from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from app.modules.limit_center.schemas import ComparisonOperator


def default_limit_rule_payloads() -> list[dict[str, Any]]:
    now = datetime.now(UTC)
    defaults: list[dict[str, Any]] = [
        _rule(
            "max_single_position_weight",
            "Max single position weight",
            "portfolio",
            "single_position_weight",
            0.25,
            "greater_than",
            "high",
            ["portfolio_builder", "risk_monitor", "trade_simulator"],
            "Largest individual holding weight must remain within policy tolerance.",
            "Compares the maximum position weight against the governance threshold.",
            now,
        ),
        _rule(
            "max_top_3_concentration",
            "Max top 3 concentration",
            "portfolio",
            "top_3_concentration",
            0.65,
            "greater_than",
            "high",
            ["portfolio_builder", "risk_monitor"],
            "Top three holdings should not dominate portfolio risk.",
            "Uses concentration analytics from Portfolio Builder or Risk Monitor.",
            now,
        ),
        _rule(
            "max_sector_exposure",
            "Max sector exposure",
            "portfolio",
            "sector_exposure",
            0.50,
            "greater_than",
            "high",
            ["portfolio_builder", "risk_monitor", "trade_simulator"],
            "Sector exposure should remain within diversification policy limits.",
            "Evaluates the largest sector weight in the supplied payload.",
            now,
        ),
        _rule(
            "min_cash_reserve",
            "Minimum cash reserve",
            "portfolio",
            "cash_weight",
            0.05,
            "less_than",
            "medium",
            ["portfolio_builder", "trade_simulator"],
            "Cash reserve should remain above the portfolio liquidity floor.",
            "Compares cash weight or post-trade cash weight against the minimum reserve.",
            now,
        ),
        _rule(
            "max_asset_class_exposure",
            "Max asset class exposure",
            "portfolio",
            "asset_class_exposure",
            0.75,
            "greater_than",
            "medium",
            ["portfolio_builder", "stress_testing"],
            "Single asset class exposure should remain diversified.",
            "Evaluates the largest asset class or asset type exposure.",
            now,
        ),
        _rule(
            "max_portfolio_volatility",
            "Max portfolio volatility",
            "risk",
            "portfolio_volatility",
            0.20,
            "greater_than",
            "high",
            ["risk_monitor", "volatility_lab"],
            "Portfolio volatility should remain below the risk policy ceiling.",
            "Uses realized, covariance-based or EWMA volatility when available.",
            now,
        ),
        _rule(
            "max_drawdown",
            "Max drawdown",
            "risk",
            "max_drawdown",
            0.15,
            "greater_than",
            "high",
            ["risk_monitor", "volatility_lab"],
            "Drawdown should remain within the approved loss tolerance.",
            "Uses absolute drawdown magnitude when supplied as a negative value.",
            now,
        ),
        _rule(
            "max_var_95",
            "Max VaR 95%",
            "risk",
            "var_95",
            0.03,
            "greater_than",
            "high",
            ["risk_monitor", "volatility_lab"],
            "One-period VaR should remain within daily loss policy.",
            "Uses historical or parametric VaR values supplied by risk modules.",
            now,
        ),
        _rule(
            "max_cvar_95",
            "Max CVaR 95%",
            "risk",
            "cvar_95",
            0.05,
            "greater_than",
            "critical",
            ["risk_monitor", "volatility_lab"],
            "Tail loss estimate should remain below the severe loss tolerance.",
            "Uses CVaR or expected shortfall metrics from risk modules.",
            now,
        ),
        _rule(
            "max_tracking_error",
            "Max tracking error",
            "risk",
            "tracking_error",
            0.08,
            "greater_than",
            "medium",
            ["risk_monitor", "volatility_lab"],
            "Active risk versus benchmark should remain controlled.",
            "Compares tracking error against active risk policy.",
            now,
        ),
        _rule(
            "max_beta",
            "Max beta",
            "risk",
            "beta",
            1.50,
            "greater_than",
            "medium",
            ["risk_monitor", "volatility_lab"],
            "Market beta should remain below the approved systematic risk ceiling.",
            "Uses beta from benchmark or volatility analytics.",
            now,
        ),
        _rule(
            "max_risk_score",
            "Max risk score",
            "risk",
            "risk_score",
            75.0,
            "greater_than",
            "critical",
            ["risk_monitor"],
            "Global risk score should not exceed the severe governance band.",
            "Evaluates Risk Monitor's global risk score.",
            now,
        ),
        _rule(
            "max_stress_loss_moderate",
            "Max moderate stress loss",
            "stress",
            "stress_loss_moderate",
            0.10,
            "greater_than",
            "medium",
            ["stress_testing"],
            "Moderate stress scenarios should remain within expected loss tolerance.",
            "Compares stress loss magnitude for moderate scenarios.",
            now,
        ),
        _rule(
            "max_stress_loss_severe",
            "Max severe stress loss",
            "stress",
            "stress_loss_severe",
            0.20,
            "greater_than",
            "critical",
            ["stress_testing"],
            "Severe stress losses above policy require immediate governance review.",
            "Compares severe scenario loss magnitude against hard tolerance.",
            now,
        ),
        _rule(
            "max_single_scenario_loss",
            "Max single scenario loss",
            "stress",
            "single_scenario_loss",
            0.15,
            "greater_than",
            "high",
            ["stress_testing"],
            "Any one stress scenario should remain within the single-scenario limit.",
            "Uses absolute percentage stress loss from Stress Testing.",
            now,
        ),
        _rule(
            "max_duration",
            "Max Macaulay duration",
            "fixed_income",
            "duration",
            7.0,
            "greater_than",
            "medium",
            ["rates_lab"],
            "Fixed-income duration should remain aligned with rate risk appetite.",
            "Compares Macaulay or portfolio duration against a seven-year ceiling.",
            now,
        ),
        _rule(
            "max_modified_duration",
            "Max modified duration",
            "fixed_income",
            "modified_duration",
            7.0,
            "greater_than",
            "high",
            ["rates_lab"],
            "Modified duration above policy increases rate sensitivity.",
            "Compares modified duration against the governance threshold.",
            now,
        ),
        _rule(
            "max_dv01",
            "Max DV01",
            "fixed_income",
            "dv01",
            50.0,
            "greater_than",
            "high",
            ["rates_lab"],
            "DV01 should remain within the demo fixed-income sensitivity budget.",
            "Uses instrument or portfolio DV01 from Rates Lab.",
            now,
        ),
        _rule(
            "max_rate_shock_loss_100bps",
            "Max rate shock loss for 100 bps",
            "fixed_income",
            "rate_shock_loss_100bps",
            0.07,
            "greater_than",
            "high",
            ["rates_lab", "stress_testing"],
            "A 100 bps rate shock should not create excessive portfolio loss.",
            "Uses rate shock loss as a percentage of portfolio or fixed-income value.",
            now,
        ),
        _rule(
            "max_delta_adjusted_exposure",
            "Max delta-adjusted exposure",
            "options",
            "delta_adjusted_exposure",
            100000.0,
            "greater_than",
            "high",
            ["options_pricing_lab"],
            "Options delta-adjusted exposure should remain within the demo risk budget.",
            "Uses aggregate or single-position delta-adjusted exposure.",
            now,
        ),
        _rule(
            "max_vega_exposure",
            "Max vega exposure",
            "options",
            "vega_exposure",
            5000.0,
            "greater_than",
            "medium",
            ["options_pricing_lab"],
            "Vega exposure should remain within volatility risk tolerance.",
            "Uses single-option or strategy vega from Options Pricing Lab.",
            now,
        ),
        _rule(
            "max_option_max_loss",
            "Max option max loss",
            "options",
            "option_max_loss",
            25000.0,
            "greater_than",
            "high",
            ["options_pricing_lab"],
            "Defined option strategy loss should remain within the demo approval budget.",
            "Compares max loss when it is finite and measurable.",
            now,
        ),
        _rule(
            "max_short_option_exposure",
            "Max short option exposure",
            "options",
            "short_option_exposure",
            50000.0,
            "greater_than",
            "high",
            ["options_pricing_lab"],
            "Short option exposure requires governance oversight.",
            "Uses short-side notional or delta-adjusted exposure when supplied.",
            now,
        ),
        _rule(
            "require_options_review_for_unlimited_loss",
            "Require review for unlimited option loss",
            "options",
            "unlimited_loss",
            True,
            "equal",
            "critical",
            ["options_pricing_lab"],
            "Unlimited-loss option strategies must be reviewed by governance.",
            "Triggers a critical breach when an options payload flags unlimited loss.",
            now,
        ),
        _rule(
            "max_trade_turnover",
            "Max trade turnover",
            "trade",
            "trade_turnover",
            0.20,
            "greater_than",
            "medium",
            ["trade_simulator"],
            "Single trade turnover should remain inside pre-trade governance tolerance.",
            "Compares gross trade value to portfolio value when available.",
            now,
        ),
        _rule(
            "min_cash_after_trade",
            "Minimum cash after trade",
            "trade",
            "cash_after_trade",
            0.05,
            "less_than",
            "high",
            ["trade_simulator"],
            "Post-trade cash should not fall below liquidity reserve.",
            "Uses cash weight after simulated trade.",
            now,
        ),
        _rule(
            "max_post_trade_single_position_weight",
            "Max post-trade single position weight",
            "trade",
            "post_trade_single_position_weight",
            0.25,
            "greater_than",
            "high",
            ["trade_simulator"],
            "Post-trade position concentration should remain within policy.",
            "Evaluates post-trade single-position weight from Trade Simulator.",
            now,
        ),
        _rule(
            "max_post_trade_sector_exposure",
            "Max post-trade sector exposure",
            "trade",
            "post_trade_sector_exposure",
            0.50,
            "greater_than",
            "high",
            ["trade_simulator"],
            "Post-trade sector concentration should remain within policy.",
            "Evaluates post-trade sector exposure from Trade Simulator.",
            now,
        ),
    ]
    return defaults


def compare_values(
    current_value: float | bool,
    limit_value: float | bool,
    operator: ComparisonOperator,
) -> bool:
    if operator == "equal":
        return current_value == limit_value
    if operator == "not_equal":
        return current_value != limit_value
    if isinstance(current_value, bool) or isinstance(limit_value, bool):
        return False
    if operator == "greater_than":
        return current_value > limit_value
    if operator == "greater_than_or_equal":
        return current_value >= limit_value
    if operator == "less_than":
        return current_value < limit_value
    if operator == "less_than_or_equal":
        return current_value <= limit_value
    return False


def _rule(
    rule_id: str,
    name: str,
    category: str,
    metric_key: str,
    limit_value: float | bool,
    comparison_operator: str,
    severity: str,
    source_modules: list[str],
    description: str,
    methodology: str,
    timestamp: datetime,
) -> dict[str, Any]:
    return {
        "rule_id": rule_id,
        "name": name,
        "category": category,
        "metric_key": metric_key,
        "limit_value": limit_value,
        "comparison_operator": comparison_operator,
        "severity_if_breached": severity,
        "enabled": True,
        "description": description,
        "source_modules": source_modules,
        "methodology": methodology,
        "created_at": timestamp,
        "updated_at": timestamp,
    }
