from app.modules.reports_center.schemas import ReportTemplate


PDF_ROADMAP_NOTE = "PDF export prepared but not enabled in this lightweight demo build."


def list_report_templates() -> list[ReportTemplate]:
    export_formats = ["json", "markdown", "csv"]
    return [
        ReportTemplate(
            report_type="portfolio_overview",
            name="Portfolio Overview Report",
            purpose="Summarize a selected portfolio and its construction profile.",
            sections=[
                "Executive summary",
                "Portfolio profile",
                "Holdings overview",
                "Asset allocation",
                "Sector allocation",
                "Geographic allocation",
                "Currency allocation",
                "Concentration analysis",
                "Benchmark",
                "Data quality",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Portfolio Builder", "Market Data", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="risk_monitor",
            name="Risk Monitor Report",
            purpose="Summarize portfolio risk, limits and risk drivers.",
            sections=[
                "Executive risk summary",
                "Risk score",
                "Volatility",
                "VaR",
                "CVaR",
                "Drawdown",
                "Tracking error",
                "Risk contribution",
                "Benchmark active risk",
                "Main risk drivers",
                "Risk warnings",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Risk Monitor", "Portfolio Builder", "Market Data", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="stress_testing",
            name="Stress Testing Report",
            purpose="Summarize stress scenario losses, drivers and limit impacts.",
            sections=[
                "Scenario selected",
                "Base portfolio value",
                "Stressed portfolio value",
                "Estimated loss",
                "Loss percentage",
                "Worst contributors",
                "Sector impact",
                "Asset class impact",
                "Before/after risk metrics",
                "Stress severity",
                "Limit breaches triggered",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Stress Testing", "Portfolio Builder", "Risk Monitor", "Limit Center"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="limit_breach",
            name="Limit Breach Report",
            purpose="Summarize governance rules, breaches and review actions.",
            sections=[
                "Overall limit status",
                "Active rules",
                "Open breaches",
                "Critical breaches",
                "Breach register",
                "Source modules",
                "Review workflow status",
                "Approved exceptions",
                "Resolved breaches",
                "Suggested governance actions",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Limit Center", "Risk Monitor", "Stress Testing", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="trade_suitability",
            name="Trade Suitability Report",
            purpose="Summarize a portfolio-aware trade simulation and suitability review.",
            sections=[
                "Trade ticket",
                "BUY/SELL action",
                "Symbol",
                "Trade size",
                "Before/after weights",
                "Cost analysis",
                "Suitability review",
                "Constraint breaches",
                "Projected post-trade risk",
                "Module source metadata",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Trade Simulator", "Portfolio Builder", "Risk Monitor", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="fixed_income_exposure",
            name="Fixed Income Exposure Report",
            purpose="Summarize rates and fixed-income risk exposure.",
            sections=[
                "Fixed income holdings",
                "Duration",
                "Modified duration",
                "Convexity",
                "DV01/PVBP",
                "Yield analysis",
                "Rate shock impact",
                "Curve scenario notes",
                "Data quality",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Rates Lab", "Portfolio Builder", "Risk Monitor", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="options_risk",
            name="Options Risk Report",
            purpose="Summarize option pricing, payoff and Greeks analytics.",
            sections=[
                "Strategy overview",
                "Option pricing model",
                "Payoff profile",
                "Greeks",
                "Delta-adjusted exposure",
                "Vega exposure",
                "Max profit/loss",
                "Breakevens",
                "Put-call parity / implied volatility notes",
                "Athena Intelligence commentary",
                "Assumptions and limitations",
            ],
            source_modules=["Options Pricing Lab", "Volatility Lab", "Risk Monitor", "Athena Intelligence"],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="pnl_attribution",
            name="P&L Attribution Report",
            purpose="Explain portfolio gains and losses by position, sector, asset class, income, trades and market drivers.",
            sections=[
                "Executive summary",
                "Portfolio and period",
                "Total P&L",
                "Realized vs unrealized P&L",
                "Income and costs",
                "Position-level P&L",
                "Asset class attribution",
                "Sector attribution",
                "Benchmark comparison",
                "Fixed income contribution",
                "Options contribution if available",
                "Trade impact",
                "Athena Intelligence commentary",
                "Methodology and limitations",
            ],
            source_modules=[
                "P&L Attribution",
                "Portfolio Builder",
                "Market Data",
                "Trade Simulator",
                "Rates Lab",
                "Options Pricing Lab",
                "Athena Intelligence",
            ],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="reconciliation",
            name="Reconciliation Report",
            purpose="Summarize position, cash, price, trade, P&L and FX breaks against demo custodian reference data.",
            sections=[
                "Executive summary",
                "Reconciliation date",
                "Portfolio",
                "Overall status",
                "Checks performed",
                "Position breaks",
                "Cash breaks",
                "Price breaks",
                "Trade breaks",
                "P&L breaks",
                "FX breaks",
                "Break severity summary",
                "Review workflow status",
                "Athena Intelligence commentary",
                "Methodology and limitations",
            ],
            source_modules=[
                "Reconciliation Center",
                "Portfolio Builder",
                "Market Data",
                "Trade Simulator",
                "P&L Attribution",
                "Athena Intelligence",
            ],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="ai_anomaly",
            name="AI Anomaly Report",
            purpose="Summarize rule-based anomaly monitoring across Athena persisted history.",
            sections=[
                "Executive summary",
                "Scan scope",
                "Lookback period",
                "Anomalies by category",
                "Anomalies by severity",
                "Top anomalies",
                "Source modules",
                "Review workflow status",
                "Suggested review priorities",
                "Athena Intelligence commentary",
                "Methodology and limitations",
            ],
            source_modules=[
                "AI Anomaly Center",
                "Market Data",
                "Portfolio Builder",
                "Trade Blotter",
                "P&L Attribution",
                "Reconciliation Center",
                "Limit Center",
                "Stress Testing",
                "Rates Lab",
                "Options Pricing Lab",
                "Athena Intelligence",
            ],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
        ReportTemplate(
            report_type="full_portfolio_risk_pack",
            name="Full Portfolio Risk Pack",
            purpose="Combine portfolio, risk, volatility, rates, stress, limits and commentary outputs.",
            sections=[
                "Portfolio Overview",
                "Risk Monitor",
                "Volatility",
                "Rates",
                "Stress Testing",
                "Limit Center",
                "Athena Intelligence synthesis",
                "Assumptions and limitations",
            ],
            source_modules=[
                "Portfolio Builder",
                "Market Data",
                "Risk Monitor",
                "Volatility Lab",
                "Rates Lab",
                "Stress Testing",
                "Limit Center",
                "Athena Intelligence",
            ],
            export_formats=export_formats,
            pdf_roadmap_note=PDF_ROADMAP_NOTE,
        ),
    ]


def get_report_template(report_type: str) -> ReportTemplate:
    for template in list_report_templates():
        if template.report_type == report_type:
            return template
    raise ValueError(f"Unknown report template: {report_type}")
